name: ci
on:
  push:
    branches:
      - 'v1'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.base
          tags: ghcr.io/terrateamio/action-base:latest
